#!/bin/bash



branches=(
    3.4
    3.4-devel
    3.4-devel-el6
    3.4-devel-el7
    3.4-el6
    3.4-el7
    3.4-testing
    3.4-testing-el6
    3.4-testing-el7
    devel
    latest
    testing
)

usage () {
    echo "${0##*/} <WORKING-DIR>"
    echo "<WORKING-DIR> should be the working directory of a git clone of"
    echo "docker-osg-wn."

    exit 2
}

set -eu

if [[ $# -ne 1 ]]; then
    usage
fi

update_one=$(readlink -f "$(dirname "$0")/update-one")
[[ -f $update_one ]] || { echo "update-one script not found; looked at $update_one" >&2; exit 1; }

repo=$(readlink -f "$1")

cd "$repo"

for branch in ${branches[@]}; do
    git checkout $branch
    $update_one "$repo"
done

echo "Verify everything is kosher and then run:"
echo "git push origin  ${branches[@]}"
