#!/bin/bash

usage () {
    echo "${0##*/} <WORKING-DIR>"
    echo "<WORKING-DIR> should be the working directory of a git clone of"
    echo "docker-osg-wn."

    exit 2
}

set -eu

if [[ $# -ne 1 ]]; then
    usage
fi

cd "$1"

DATE=$(date +%Y%m%d-%H%M)
BRANCH=$(git branch | fgrep '*' | cut -c 3-)
WD_ROOT=$(git rev-parse --show-toplevel)

cd "$WD_ROOT"

if ! fgrep -qs '@BUILDDATE@' Dockerfile.in; then
    echo "No usable Dockerfile.in on this branch - skipping"
    exit 0
fi

sed -e '1i\
# GENERATED - EDIT Dockerfile.in INSTEAD' \
    -e "s/@BUILDDATE@/$DATE/" \
    Dockerfile.in > Dockerfile

git add Dockerfile
git commit -m "New build of $BRANCH at $DATE"
